README.md
generated/Keboola/StorageDriver/Command/Workspace/ResetWorkspacePasswordCommand.php
proto/workspace.proto
src/Handler/Backend/Init/InitBackendHandler.php
src/Handler/Project/Create/CreateProjectHandler.php
src/Handler/Workspace/ResetPassword/ResetWorkspacePasswordHandler.php
src/TeradataDriverClient.php
tests/functional/UseCase/Workspace/ResetWorkspacePasswordTest.php

Jira: https://keboola.atlassian.net/browse/KBC-2431

workspace reset password

---

src/Handler/Workspace/Clear/ClearWorkspaceHandler.php
src/TeradataDriverClient.php
tests/functional/UseCase/Workspace/ClearWorkspaceTest.php

workspace: clear command

---

proto/workspace.proto
src/Handler/Workspace/DropObject/DropWorkspaceObjectHandler.php
src/TeradataDriverClient.php
tests/functional/UseCase/Workspace/DropWorkspaceObjectTest.php

workspace: object drop

---

Dockerfile
composer.json
docker-compose.yaml
src/Handler/Table/Create/CreateTableHandler.php
src/Handler/Table/Drop/DropTableHandler.php
src/Handler/Table/Preview/PreviewTableHandler.php
src/Handler/Workspace/Clear/ClearWorkspaceHandler.php
src/Handler/Workspace/Create/CreateWorkspaceHandler.php
src/Handler/Workspace/Drop/DropWorkspaceHandler.php
src/Handler/Workspace/DropObject/DropWorkspaceObjectHandler.php
src/Handler/Workspace/ResetPassword/ResetWorkspacePasswordHandler.php
tests/functional/UseCase/Bucket/CreateDropBucketTest.php
tests/functional/UseCase/Table/ImportTableFromFileTest.php
tests/functional/UseCase/Workspace/ClearWorkspaceTest.php
tests/functional/UseCase/Workspace/CreateDropWorkspaceTest.php
tests/functional/UseCase/Workspace/DropWorkspaceObjectTest.php
tests/functional/UseCase/Workspace/ResetWorkspacePasswordTest.php

- oprava assertů, když je sloupec nebo tabulka '0' tak to musí projít empty() není vhodný check.
- update import lib
- díky změně z PDO přímo jen na ODBC se zavře link když sa otevře jiný pro stejné credentilas, moc sem to nezkoumal dělá to problémy jen v testech, docela zajímavé, že když sa použije PDO tak je to cajk.

Fix 0 col, update deps

---

composer.json

K TD tam nic není, musím akorát udělat kolečko než bude I/E v1

use keboola/db-import-export 0.24

---

src/ConnectionFactory.php
src/Handler/Bucket/Share/ShareBucketHandler.php
tests/functional/BaseCase.php
tests/functional/UseCase/Bucket/ShareLinkBucketTest.php
tests/functional/UseCase/Workspace/ClearWorkspaceTest.php
tests/functional/UseCase/Workspace/CreateDropWorkspaceTest.php

Jira: https://keboola.atlassian.net/browse/TER-56
Share bucekt. Share only.

TER-56 share bucket

---

src/Handler/Bucket/Link/LinkBucketHandler.php
src/Handler/Project/Create/CreateProjectHandler.php
tests/functional/UseCase/Bucket/ShareLinkBucketTest.php

Jira: https://keboola.atlassian.net/browse/TER-57
link only

TER-57 link bucket

---

src/Handler/Bucket/UnLink/UnLinkBucketHandler.php
src/Handler/Bucket/UnShare/UnShareBucketHandler.php
tests/functional/UseCase/Bucket/ShareLinkBucketTest.php

Jira: TER-56 TER-57
undo operations - unshare and unlink

TER-56 57 unlink unshare

---

src/TeradataDriverClient.php

Add sharing classes to driver client

---

src/Handler/Table/Create/CreateTableHandler.php
tests/functional/UseCase/Table/CreateDropTableTest.php
tests/functional/UseCase/Table/PreviewTableTest.php

Pridam v response create table aby to vratilo TableInfo upravil som aj BQ driver este poslem PR do connection 
Uprava v BigQuery: https://github.com/keboola/php-storage-driver-teradata/pull/42

CreateTableHandler return table info

---

composer.json
src/Handler/Table/Import/ImportTableFromFileHandler.php
src/Handler/Table/Import/ImportTableFromTableHandler.php
tests/functional/BaseCase.php
tests/functional/UseCase/Table/ImportTableFromFileTest.php
tests/functional/UseCase/Table/ImportTableFromTableTest.php

Jira: TER-70
use [IE](https://github.com/keboola/php-db-import-export/pull/153/commits/2f3e24a2678b85cdcb1fb27d649ce38c2da7197a) importers for Inc load from File and Table

TER-70 inc load from file

---

.gitignore
composer.json
src/Handler/Table/Preview/PreviewTableHandler.php
src/QueryBuilder/TableFilterQueryBuilder.php
tests/functional/UseCase/Table/PreviewTableTest.php
tests/unit/QueryBuilder/TableFilterQueryBuilderTest.php

Jira: TER-77
driver-common: https://github.com/keboola/php-storage-driver-common/pull/19
connection: https://github.com/keboola/connection/pull/4097
Composer dev branches:
```
$ dcrr dev composer update keboola/storage-driver-common
"keboola/storage-driver-common": "dev-TER-77-repeated-orderBy as 1.4.0",
```

TER-77 repeated order by

---

composer.json
etc/docker/xdebug/Dockerfile
src/Handler/Bucket/Link/LinkBucketHandler.php
src/Handler/Bucket/Share/ShareBucketHandler.php
tests/functional/UseCase/Bucket/ShareLinkBucketTest.php

Jira: TER-85
update Share/Link handlers based on https://github.com/keboola/php-storage-driver-common/pull/18

TER-85 Use new form of share/link command

---

composer.json
src/Handler/Table/Alter/AddColumnHandler.php
src/Handler/Table/Alter/DropColumnHandler.php
src/Handler/Table/Create/CreateTableHandler.php
src/TeradataDriverClient.php
tests/functional/BaseCase.php
tests/functional/UseCase/Table/AddDropColumnTest.php
tests/functional/UseCase/Table/CreateDropTableTest.php
tests/functional/UseCase/Table/PreviewTableTest.php

Jira: TER-58
Handler to add/drop col
Table utils: https://github.com/keboola/php-table-backend-utils/pull/88
Common: https://github.com/keboola/php-storage-driver-common/pull/21
TD Driver: https://github.com/keboola/php-storage-driver-teradata/pull/49
BQ Driver: https://github.com/keboola/php-storage-driver-bigquery/pull/27 
Connection: https://github.com/keboola/connection/pull/4120
SAPI: https://github.com/keboola/storage-api-php-client/pull/960

TER-58 init add column handler

---

src/Handler/Table/Import/ImportTableFromFileHandler.php
tests/functional/UseCase/Table/ImportBaseCase.php
tests/functional/UseCase/Table/ImportTableFromFileTest.php
tests/functional/UseCase/Table/ImportTableFromTableTest.php

Jira: TER-XXX
[tady](https://github.com/keboola/php-storage-driver-teradata/pull/50) jsem pridal ImportStrategy, ale jen do ImportFromFile, ale ne do ImportFromTable, tak to tady fixuju
A tsety byly v tom starem PR krizem (pridal jsem to do ImportFromFile, ale testy byly v ImportFromTable), tak tady taktez fixuju. A rovnou jsem cast kodu predal do abstraktni tridy, at se to nemusi duplikovat

use importStrategy on both imports

---

src/Handler/Table/Alter/DeleteTableRowsHandler.php
src/Handler/Table/Export/ExportTableToFileHandler.php
src/Handler/Table/Preview/PreviewTableHandler.php
src/QueryBuilder/CommonFilterQueryBuilder.php
src/QueryBuilder/ExportQueryBuilder.php
src/TeradataDriverClient.php
tests/functional/BaseCase.php
tests/functional/UseCase/Table/DeleteTableRowsTest.php
tests/unit/QueryBuilder/ExportQueryBuilderTest.php

Jira: TER-87
Connection: https://github.com/keboola/connection/pull/4146

TER-87 delete rows

---

composer.json
src/Handler/Bucket/Create/GrantBucketAccessToReadOnlyRoleHandler.php
src/Handler/Bucket/Create/GrantBucketToRO.php
src/TeradataDriverClient.php
tests/functional/UseCase/Bucket/GrantBucketAccessToReadOnlyRoleTest.php

Jira: TER-99
Common: https://github.com/keboola/php-storage-driver-common/pull/32
TD driver: https://github.com/keboola/php-storage-driver-teradata/pull/55
Connection: https://github.com/keboola/connection/pull/4160
SAPI https://github.com/keboola/storage-api-php-client/pull/981
grantuje select nad tim ext bucketem do RO, aby se to dalo pouzit ve WS

TER-99 grant bucket to RO

---

src/DbUtils.php
src/Handler/Bucket/Drop/DropBucketHandler.php
src/Handler/Project/Drop/DropProjectHandler.php
src/Handler/Workspace/Drop/DropWorkspaceHandler.php
src/Handler/Workspace/DropObject/DropWorkspaceObjectHandler.php
tests/functional/BaseCase.php
tests/functional/UseCase/Bucket/CreateDropBucketTest.php
tests/functional/UseCase/Bucket/ShareLinkBucketTest.php
tests/functional/UseCase/Project/CreateDropProjectTest.php
tests/functional/UseCase/Table/CreateDropTableTest.php
tests/functional/UseCase/Table/ExportTableToFileTest.php
tests/functional/UseCase/Workspace/ClearWorkspaceTest.php
tests/functional/UseCase/Workspace/CreateDropWorkspaceTest.php
tests/functional/UseCase/Workspace/DropWorkspaceObjectTest.php
tests/unit/DbUtilsTest.php

Jira: TER-92
Connection PR: https://github.com/keboola/connection/pull/4075

TER-92 cascade drop

---

composer.json
src/Handler/Bucket/Drop/RevokeBucketAccessFromReadOnlyRoleHandler.php
src/TeradataDriverClient.php
tests/functional/UseCase/Bucket/GrantRevokeBucketAccessToReadOnlyRoleTest.php

Jira: TER-103
driver-common: https://github.com/keboola/php-storage-driver-common/pull/34
Connection: https://github.com/keboola/connection/pull/4193

TER-103 external bucket drop role

---

src/Handler/Exception/ExceptionResolver.php
src/Handler/Exception/RowSizeTooLargeException.php
src/Handler/Exception/TooManyColumnsException.php
src/Handler/Table/Alter/AddColumnHandler.php
src/Handler/Table/Create/CreateTableHandler.php

Jira: TER-89
Connection: https://github.com/keboola/connection/pull/4199
Osetreni chyb:
- 3919   Table has too many columns. ([doc](https://docs.teradata.com/r/bBJcqMYyoxECDlJRAz9Dgw/41k1Cl3VSGevNbfgvlZE3Q))
- 3933   The available data bytes in the table's perm row has exceeded the %VSTR byte limit. ([doc](https://docs.teradata.com/r/bBJcqMYyoxECDlJRAz9Dgw/41k1Cl3VSGevNbfgvlZE3Q))

TER-89 check too many columns

---

Dockerfile
composer.json
src/DebugLogger.php
tests/functional/BaseCase.php
tests/functional/StorageHelper/StorageTrait.php
tests/functional/TestsLogger.php
tests/functional/UseCase/Info/ObjectInfoTest.php

use php8.1

---

composer.json
src/TeradataDriverClient.php
tests/unit/TeradataDriverClientTest.php

Jira: BIG-153
adding runtime options to be compatible with BQ

use new interface with runtime options
